version: '4.0'

actions:
  generate_dataset:
    run: ehrql:v1 generate-dataset analysis/dataset_definition.py --dummy-tables dummy_tables --output output/dataset.csv
    outputs:
      highly_sensitive:
        dataset: output/dataset.csv
